/*
 * OTA Firmware Signing — ED25519 signature verification via PSA Crypto.
 *
 * Uses the PSA Crypto API (PSA_ALG_PURE_EDDSA) provided by NCS nrf_security.
 * The nRF52840's CC310 does not support Ed25519, so verification runs via
 * the Oberon software backend (CONFIG_PSA_WANT_ALG_PURE_EDDSA=y).
 *
 * The 32-byte public key below must match the private key generated by:
 *   python3 aws/ota_deploy.py keygen
 *
 * For host-side unit tests, mock_ota_signing.c replaces this entire file.
 */

#include <ota_signing.h>

#include <psa/crypto.h>
#include <zephyr/logging/log.h>

LOG_MODULE_REGISTER(ota_signing, CONFIG_SIDEWALK_LOG_LEVEL);

/* 32-byte ED25519 public key — generated by:
 *   python3 aws/ota_deploy.py keygen
 *
 * Replace with your deployment key. All-zeros key will fail verification
 * for any valid signature.
 */
static const uint8_t ota_public_key[32] = {
	0x70, 0xf3, 0xb4, 0xb0, 0x5b, 0x82, 0x0e, 0x0c,
	0x5f, 0x88, 0xf6, 0x62, 0xfa, 0xb8, 0x3b, 0x24,
	0x94, 0x8f, 0x24, 0xac, 0x24, 0x08, 0xfd, 0x43,
	0xa0, 0xc4, 0xa3, 0xfa, 0xf2, 0xe0, 0xad, 0xb2,
};

int ota_verify_signature(const uint8_t *data, size_t len, const uint8_t *sig)
{
	psa_status_t status;
	psa_key_id_t key_id = 0;
	psa_key_attributes_t attr = PSA_KEY_ATTRIBUTES_INIT;

	/* Configure key attributes for Ed25519 public key, verify-only */
	psa_set_key_type(&attr,
		PSA_KEY_TYPE_ECC_PUBLIC_KEY(PSA_ECC_FAMILY_TWISTED_EDWARDS));
	psa_set_key_algorithm(&attr, PSA_ALG_PURE_EDDSA);
	psa_set_key_usage_flags(&attr, PSA_KEY_USAGE_VERIFY_MESSAGE);
	psa_set_key_bits(&attr, 255);

	/* Import the public key as a volatile PSA key */
	status = psa_import_key(&attr, ota_public_key,
				sizeof(ota_public_key), &key_id);
	if (status != PSA_SUCCESS) {
		LOG_ERR("OTA sign: key import failed (PSA %d)", (int)status);
		return -1;
	}

	/* Verify ED25519 signature over the firmware data */
	status = psa_verify_message(key_id, PSA_ALG_PURE_EDDSA,
				    data, len, sig, OTA_SIG_SIZE);

	psa_destroy_key(key_id);

	if (status != PSA_SUCCESS) {
		LOG_WRN("OTA sign: verification failed (PSA %d)", (int)status);
		return -2;
	}

	LOG_INF("OTA sign: ED25519 signature verified OK");
	return 0;
}
